from enum import Enum

class CodigoError(str, Enum):
    # Errores de imagen (formato/decodificacion)
    IMAGEN_INVALIDA = "IMAGEN_INVALIDA"
    IMAGEN_NO_DECODIFICABLE_ACTUAL = "IMAGEN_NO_DECODIFICABLE_ACTUAL"
    IMAGEN_NO_DECODIFICABLE_REFERENCIA = "IMAGEN_NO_DECODIFICABLE_REFERENCIA"

    # Errores de rostro
    ROSTRO_ACTUAL_NO_DETECTADO = "ROSTRO_ACTUAL_NO_DETECTADO"
    ROSTRO_REFERENCIA_NO_DETECTADO = "ROSTRO_REFERENCIA_NO_DETECTADO"

    MULTIPLES_ROSTROS_ACTUAL = "MULTIPLES_ROSTROS_ACTUAL"
    MULTIPLES_ROSTROS_REFERENCIA = "MULTIPLES_ROSTROS_REFERENCIA"

    RESOLUCION_INVALIDA_ACTUAL = "RESOLUCION_INVALIDA_ACTUAL"
    RESOLUCION_INVALIDA_REFERENCIA = "RESOLUCION_INVALIDA_REFERENCIA"

    ILUMINACION_INVALIDA_ACTUAL = "ILUMINACION_INVALIDA_ACTUAL"
    ILUMINACION_INVALIDA_REFERENCIA = "ILUMINACION_INVALIDA_REFERENCIA"

    NITIDEZ_INVALIDA_ACTUAL = "NITIDEZ_INVALIDA_ACTUAL"
    NITIDEZ_INVALIDA_REFERENCIA = "NITIDEZ_INVALIDA_REFERENCIA"

    DISTANCIA_INVALIDA_ACTUAL = "DISTANCIA_INVALIDA_ACTUAL"
    DISTANCIA_INVALIDA_REFERENCIA = "DISTANCIA_INVALIDA_REFERENCIA"

    ANGULO_INVALIDO_ACTUAL = "ANGULO_INVALIDO_ACTUAL"
    ANGULO_INVALIDO_REFERENCIA = "ANGULO_INVALIDO_REFERENCIA"

    # Confianza de deteccion (det_score de SCRFD) por debajo del minimo aceptable
    DETECCION_BAJA_CONFIANZA_ACTUAL = "DETECCION_BAJA_CONFIANZA_ACTUAL"
    DETECCION_BAJA_CONFIANZA_REFERENCIA = "DETECCION_BAJA_CONFIANZA_REFERENCIA"

    EMBEDDING_INVALIDO_ACTUAL = "EMBEDDING_INVALIDO_ACTUAL"
    EMBEDDING_INVALIDO_REFERENCIA = "EMBEDDING_INVALIDO_REFERENCIA"

    # Solicitud mal formada no cubierta por un codigo mas especifico
    # (ej. campo desconocido/faltante detectado por la validacion de Pydantic)
    SOLICITUD_INVALIDA = "SOLICITUD_INVALIDA"

    # Autenticacion (JWT)
    TOKEN_FALTANTE = "TOKEN_FALTANTE"
    TOKEN_INVALIDO = "TOKEN_INVALIDO"
    TOKEN_EXPIRADO = "TOKEN_EXPIRADO"
    CREDENCIALES_INVALIDAS = "CREDENCIALES_INVALIDAS"

    # Catch-all para errores no anticipados del lado del servidor
    # (fallo del modelo, timeout, etc.)
    ERROR_INTERNO = "ERROR_INTERNO"

class TipoImagen(str, Enum):
    ACTUAL = "actual"
    REFERENCIA = "referencia"

class ResultadoVerificacion(str, Enum):
    COINCIDE = "COINCIDE"
    NO_COINCIDE = "NO_COINCIDE"

class Distancia(str, Enum):
    CERCA = "CERCA"
    LEJOS = "LEJOS"
    CORRECTA = "CORRECTA"

class Angulo(str, Enum):
    FRONTAL = "FRONTAL"
    PERFIL = "PERFIL"
    INCLINADO = "INCLINADO"